set(SOURCES
  fa_policy.cpp
  forests_policy.cpp
  monte_carlo_policy.cpp
  random_policy.cpp
  policy_factory.cpp
  history.cpp
  opportunist_policy.cpp
  policy.cpp
  problem.cpp
  problem_factory.cpp
  sample.cpp
)
